filter:
  excluded_paths:
    - 'vendor/*'
    - '.github/*'
    - 'examples/*'
    - 'tests/*'
  paths:
    - 'src/*'

build:
  image: default-noble
  environment:
    php:
      version: '8.4'
  dependencies:
    before:
      - wget -O composer.phar https://getcomposer.org/composer.phar
      - chmod +x composer.phar
      - ./composer.phar install
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover tests/data/clover.xml
            coverage:
              file:  tests/data/clover.xml
              format: php-clover

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true
